name: Functionnal Test

on:
  push:

jobs:
  functionnal_tests:
    name: "Run functionnal tests"
    runs-on: ubuntu-latest
    container: golang:1.18-alpine
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: build
        run: go build -o GinGen main.go
      - name: Run binary
        run: ./GinGen -i $(pwd)/demo/testing_file -o $(pwd)/demo/output_test.json -c $(pwd)/demo/components.json
      - name: Compare output
        run: diff $(pwd)/demo/output_test.json $(pwd)/demo/default_output.json
        timeout-minutes: 2
