name: Unit tests

on:
  push:

jobs:
  unit_tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    container: golang:1.18-alpine
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Unit tests
        run: go test -v ./...
        timeout-minutes: 2
